print(" ")
print("-------------------------------------------")
print("|      Loading Intercom System Files      |")
print("|        Addon created by mr_flolo        |")
print("-------------------------------------------")
print(" ")
